name: StratumEconomy
version: ${project.version}
main: tech.quilldev.stratumeconomy.StratumEconomy
api-version: 1.16
depend: [ Vault ]

commands:
  reloadmarket:
    description: Reloads the market values from the online database
    permission: stratumeconomy.admin.reloadmarket
    usage: /<command>
  addvendoritem:
    description: Adds a market item to the given merchant
    permission: stratumeconomy.admin.additem.dynamic
    usage: /<command> <item>
